---
title: "Tercera parte (R y Python): Calidad del café"
author:
  - "Brenda Poulette Torres Vargas"
  - "Diego Betancourt Peralta"
  - "Erick Iván Canul Hernández"
  - "José Omar Gutiérrez Gutiérrez"
  - "Maximiliano Hernández Pérez"
format: html
---

# Instrucciones:

Se usará el conjunto de datos de encuesta de café (`coffee_ratings.csv`).

-   Actividad 0: Realice un análisis de valores faltantes del objeto `datos`
-   Actividad 1: Crear una columna llamada `color2` que se base en los valores de la columna `color`, que asigne el valor NA si `color == NA`, "#00FF66" si `color == 'Green'`, "#CCEBC5" si `color == 'Bluish-green'` y "#BFFFFF" si `color == 'Blue-green'`
-   Actividad 2: Crear una columna llamada `bag_weight2` que se base en los valores de la columna `bag_weight`, que sólo contenga el valor numérico de ésta. Es decir, `bag_weight2` debe ser numérica. ¿Cuántas observaciones llevaron a ambigüedad para crear esta nueva columna?
-   Actividad 3: Crear dos columnas llamadas `method1` y `method2` que se basen en los valores de la columna `processing_method`, dividiendo en dos partes los valores dicha columna. ¿Cuántas observaciones llevaron a ambigüedad para crear esta nueva columna?
-   Actividad 4: Crear tres columnas llamadas `expiration_day`, `expiration_month` y `expiration_year` que se basen en los valores de la columna `expiration`. ¿Cuántas observaciones llevaron a ambigüedad para crear estas nuevas columnas?
-   Actividad 5: Crear dos columnas llamadas `harvest_mes` y `harvest_anio` que se basen en los valores de la columna `harvest_year`, dividiendo en dos partes los valores dicha columna. ¿Cuántas observaciones llevaron a ambigüedad para crear esta nueva columna?
-   Actividad 6: Elabore una visualización con `ggplot2` que identifique alguna relación entre las columnas total_cup_points, acidity y color2 de tal forma que se puedan identificar los colores de la variable `color2`. Es decir, debemos ver los colores, "#00FF66", "#CCEBC5" y "#BFFFFF".
-   Actividad 7: Elabore una visualización de densidad con `ggplot2` de la variable `bag_weight2` diferenciando a los valores de `species`.
-   Actividad 8: Elabore una visualización que relacione el año/mes de expiración con el `total_cup_points` sólo de los granos mexicanos, brasileños, colombianos y guatemaltecos.
-   Actividad 9: Elabore una visualización con `ggplot2` que relacione el mes de expiración con el `altitude_mean_meters`, `altitude_low_meters` y `altitude_high_meters` sólo de los granos mexicanos, brasileños, colombianos y guatemaltecos de los años de expiración 2016 y 2017.
-   Actividad 10: Elabore una visualización con `ggplot2` que relacione el `aftertaste`, `acidity`, `body` y `species` en un mismo canvas.

*Importante:* Sus visualizaciones deben tener formato suficientemente bueno para publicar en alguna revista.
